[package]
name = "nivren-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
nivren = { path = ".." }

[[bin]]
name = "frontend"
path = "fuzz_targets/frontend.rs"
test = false
doc = false
bench = false

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
test = false
doc = false
bench = false
