//! Deterministic schema-driven foreign binding generation.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ast::{Stmt, TypeRef};
use crate::error::NivError;

pub fn c_header(program: &[Stmt]) -> Result<String, NivError> {
    let mut shapes = BTreeMap::new();
    let mut choices = BTreeMap::new();
    collect(program, &mut shapes, &mut choices);
    if shapes.is_empty() && choices.is_empty() {
        return Err(NivError::new(
            "binding generation needs at least one shape or choice",
            1,
            1,
        ));
    }
    let mut names = BTreeSet::new();
    for name in shapes.keys().chain(choices.keys()) {
        let generated = c_name(name);
        if !names.insert(generated.clone()) {
            return Err(NivError::new(
                format!("schema names collide after C identifier conversion: {generated}"),
                1,
                1,
            ));
        }
    }

    let shape_names: BTreeSet<_> = shapes.keys().cloned().collect();
    let choice_names: BTreeSet<_> = choices.keys().cloned().collect();
    let mut output = String::from(
        "/* Generated by `niv bindgen c`; do not edit. */\n\
         #ifndef NIVREN_GENERATED_BINDINGS_H\n\
         #define NIVREN_GENERATED_BINDINGS_H\n\n\
         #include <stddef.h>\n\
         #include <stdint.h>\n\n\
         #ifdef __cplusplus\n\
         extern \"C\" {\n\
         #endif\n\n\
         typedef struct NivrenStringView { const uint8_t *data; size_t length; } NivrenStringView;\n\
         typedef struct NivrenBytesView { const uint8_t *data; size_t length; } NivrenBytesView;\n\
         typedef struct NivrenValueView { const uint8_t *json; size_t length; } NivrenValueView;\n\n",
    );
    for name in shapes.keys() {
        let generated = c_name(name);
        writeln!(
            output,
            "typedef struct Nivren_{generated} Nivren_{generated};"
        )
        .unwrap();
    }
    if !shapes.is_empty() {
        output.push('\n');
    }
    for (name, variants) in &choices {
        let generated = c_name(name);
        writeln!(output, "typedef enum Nivren_{generated} {{").unwrap();
        for (index, variant) in variants.iter().enumerate() {
            writeln!(
                output,
                "    NIVREN_{}_{} = {index},",
                generated.to_ascii_uppercase(),
                c_name(variant).to_ascii_uppercase()
            )
            .unwrap();
        }
        writeln!(output, "}} Nivren_{generated};\n").unwrap();
    }
    for (name, fields) in &shapes {
        let generated = c_name(name);
        writeln!(output, "struct Nivren_{generated} {{").unwrap();
        for (field, ty) in fields {
            let field = c_name(field);
            writeln!(
                output,
                "    {};",
                c_declaration(ty, &field, &shape_names, &choice_names)
            )
            .unwrap();
        }
        output.push_str("};\n\n");
    }
    output.push_str(
        "#ifdef __cplusplus\n\
         }\n\
         #endif\n\n\
         #endif\n",
    );
    Ok(output)
}

fn collect(
    statements: &[Stmt],
    shapes: &mut BTreeMap<String, Vec<(String, TypeRef)>>,
    choices: &mut BTreeMap<String, Vec<String>>,
) {
    for statement in statements {
        match statement {
            Stmt::Record { name, fields, .. } => {
                shapes.insert(
                    name.clone(),
                    fields
                        .iter()
                        .map(|field| (field.name.clone(), field.ty.clone()))
                        .collect(),
                );
            }
            Stmt::Enum { name, variants, .. } => {
                choices.insert(
                    name.clone(),
                    variants
                        .iter()
                        .map(|variant| variant.name.clone())
                        .collect(),
                );
            }
            Stmt::Module { name, body, .. } => {
                let mut nested_shapes = BTreeMap::new();
                let mut nested_choices = BTreeMap::new();
                collect(body, &mut nested_shapes, &mut nested_choices);
                shapes.extend(
                    nested_shapes
                        .into_iter()
                        .map(|(item, fields)| (format!("{name}_{item}"), fields)),
                );
                choices.extend(
                    nested_choices
                        .into_iter()
                        .map(|(item, variants)| (format!("{name}_{item}"), variants)),
                );
            }
            _ => {}
        }
    }
}

fn c_declaration(
    ty: &TypeRef,
    name: &str,
    shapes: &BTreeSet<String>,
    choices: &BTreeSet<String>,
) -> String {
    match ty {
        TypeRef::Array(item, _) => format!(
            "struct {{ const {} *data; size_t length; }} {name}",
            c_element_type(item, shapes, choices)
        ),
        TypeRef::Nullable(item, _) => format!(
            "struct {{ uint8_t has_value; {}; }} {name}",
            c_declaration(item, "value", shapes, choices)
        ),
        TypeRef::Applied(kind, arguments, _) if kind == "Array" && arguments.len() == 1 => {
            format!(
                "struct {{ const {} *data; size_t length; }} {name}",
                c_element_type(&arguments[0], shapes, choices)
            )
        }
        TypeRef::Applied(_, _, _) | TypeRef::Result(_, _, _) => {
            format!("NivrenValueView {name}")
        }
        TypeRef::Named(kind, _) => format!("{} {name}", c_named_type(kind, shapes, choices)),
    }
}

fn c_element_type(ty: &TypeRef, shapes: &BTreeSet<String>, choices: &BTreeSet<String>) -> String {
    match ty {
        TypeRef::Named(name, _) => c_named_type(name, shapes, choices),
        _ => "NivrenValueView".into(),
    }
}

fn c_named_type(name: &str, shapes: &BTreeSet<String>, choices: &BTreeSet<String>) -> String {
    match name {
        "Int" => "int64_t".into(),
        "Float" => "double".into(),
        "Bool" => "uint8_t".into(),
        "I8" => "int8_t".into(),
        "I16" => "int16_t".into(),
        "I32" => "int32_t".into(),
        "U8" => "uint8_t".into(),
        "U16" => "uint16_t".into(),
        "U32" => "uint32_t".into(),
        "U64" => "uint64_t".into(),
        "String" | "BigInt" | "Decimal" | "DateTime" => "NivrenStringView".into(),
        "Bytes" => "NivrenBytesView".into(),
        "Nothing" => "uint8_t".into(),
        _ if shapes.contains(name) => format!("const Nivren_{} *", c_name(name)),
        _ if choices.contains(name) => format!("Nivren_{}", c_name(name)),
        _ => "NivrenValueView".into(),
    }
}

fn c_name(name: &str) -> String {
    let mut output = String::new();
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            output.push(character);
        } else {
            write!(output, "_u{:x}_", character as u32).unwrap();
        }
    }
    if output.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        output.insert(0, '_');
    }
    output
}

#[cfg(test)]
mod tests {
    use super::c_header;

    #[test]
    fn c_bindings_are_deterministic_and_typed() {
        let source = r#"
choice Role { Admin, Member }
shape Address { city is String, postal is U32 }
shape User { name is String, role is Role, address is Address?, tags is [String] }
"#;
        let program = crate::parser::parse(crate::lexer::scan(source).unwrap()).unwrap();
        crate::typecheck::check(&program).unwrap();
        let first = c_header(&program).unwrap();
        let second = c_header(&program).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("typedef enum Nivren_Role"));
        assert!(first.contains("NIVREN_ROLE_ADMIN = 0"));
        assert!(first.contains("uint32_t postal;"));
        assert!(first.contains("const Nivren_Address * value"));
        assert!(first.contains("const NivrenStringView *data"));
    }
}
