use crate::ast::{FieldDef, Param, Stmt, TypeRef};

pub fn generate(package: &str, version: &str, program: &[Stmt]) -> String {
    let mut output = format!(
        "# {package} {version} API\n\nGenerated by Nivren {}.\n",
        crate::VERSION
    );
    document_entry_exports(program, &mut output);
    document_modules(program, &mut output);
    output
}

fn document_entry_exports(statements: &[Stmt], output: &mut String) {
    let Some(exports) = statements.iter().find_map(|statement| match statement {
        Stmt::Export { names, .. } => Some(names),
        _ => None,
    }) else {
        return;
    };
    output.push_str("\n## Public API\n\n");
    for export in exports {
        if let Some(position) = statements
            .iter()
            .position(|item| declared_name(item) == Some(export))
        {
            output.push_str(&format!(
                "- {}\n",
                declaration_signature(&statements[position])
            ));
            push_doc_text(statements, position, output);
        }
    }
}

fn push_doc_text(statements: &[Stmt], position: usize, output: &mut String) {
    if position == 0 {
        return;
    }
    if let Stmt::Doc { text, .. } = &statements[position - 1] {
        for line in text.lines() {
            output.push_str(&format!("  {line}\n"));
        }
    }
}

fn document_modules(statements: &[Stmt], output: &mut String) {
    for statement in statements {
        if let Stmt::Module {
            name,
            body,
            exports,
            ..
        } = statement
        {
            output.push_str(&format!("\n## Module `{name}`\n\n"));
            for export in exports {
                if let Some(position) = body
                    .iter()
                    .position(|item| declared_name(item) == Some(export))
                {
                    output.push_str(&format!("- {}\n", declaration_signature(&body[position])));
                    push_doc_text(body, position, output);
                }
            }
            document_modules(body, output);
        }
    }
}

fn declared_name(statement: &Stmt) -> Option<&String> {
    match statement {
        Stmt::Let { name, .. }
        | Stmt::Function { name, .. }
        | Stmt::Record { name, .. }
        | Stmt::Enum { name, .. }
        | Stmt::Protocol { name, .. }
        | Stmt::Module { name, .. } => Some(name),
        _ => None,
    }
}

fn declaration_signature(statement: &Stmt) -> String {
    match statement {
        Stmt::Let {
            name, annotation, ..
        } => annotation.as_ref().map_or_else(
            || format!("`keep {name}`"),
            |ty| format!("`keep {name}: {}`", type_name(ty)),
        ),
        Stmt::Function {
            name,
            type_params,
            params,
            return_type,
            needs,
            capability_needs,
            ..
        } => {
            let generics = if type_params.is_empty() {
                String::new()
            } else {
                format!(
                    "<{}>",
                    type_params
                        .iter()
                        .map(|parameter| parameter.constraint.as_ref().map_or_else(
                            || parameter.name.clone(),
                            |constraint| format!("{} is {constraint}", parameter.name)
                        ))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            };
            let parameters = params.iter().map(param_name).collect::<Vec<_>>().join(", ");
            let result = return_type
                .as_ref()
                .map(|ty| format!(" gives {}", type_name(ty)))
                .unwrap_or_default();
            let capabilities = if capability_needs.iter().any(|need| need.boundary.is_some()) {
                format!(
                    " needs {}",
                    capability_needs
                        .iter()
                        .map(|need| need.boundary.as_ref().map_or_else(
                            || need.capability.clone(),
                            |boundary| format!("{} within \"{}\"", need.capability, boundary)
                        ))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            } else if needs.is_empty() {
                String::new()
            } else {
                format!(" needs {}", needs.join(", "))
            };
            format!("`define {name}{generics} takes {{ {parameters} }}{result}{capabilities}`")
        }
        Stmt::Record {
            name,
            type_params,
            fields,
            derives,
            ..
        } => {
            let generics = generic_parameters(type_params);
            let fields = fields.iter().map(field_name).collect::<Vec<_>>().join(", ");
            let derives = if derives.is_empty() {
                String::new()
            } else {
                format!(" derives {}", derives.join(", "))
            };
            format!("`shape {name}{generics} {{ {fields} }}{derives}`")
        }
        Stmt::Enum {
            name,
            type_params,
            variants,
            ..
        } => {
            let generics = generic_parameters(type_params);
            let variants = variants
                .iter()
                .map(|variant| {
                    variant.payload.as_ref().map_or_else(
                        || variant.name.clone(),
                        |payload| format!("{}({})", variant.name, type_name(payload)),
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("`choice {name}{generics} {{ {variants} }}`")
        }
        Stmt::Protocol { name, members, .. } => {
            if members.is_empty() {
                format!("`protocol {name}`")
            } else {
                let members = members
                    .iter()
                    .map(|member| {
                        let parameters = member
                            .params
                            .iter()
                            .map(param_name)
                            .collect::<Vec<_>>()
                            .join(", ");
                        let needs = if member.needs.is_empty() {
                            String::new()
                        } else {
                            format!(" needs {}", member.needs.join(", "))
                        };
                        format!(
                            "define {}({parameters}) gives {}{needs}",
                            member.name,
                            type_name(&member.return_type)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("; ");
                format!("`protocol {name} {{ {members} }}`")
            }
        }
        Stmt::Module { name, .. } => format!("`module {name}`"),
        _ => "`unknown declaration`".into(),
    }
}

fn generic_parameters(parameters: &[crate::ast::TypeParam]) -> String {
    if parameters.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            parameters
                .iter()
                .map(|parameter| parameter.constraint.as_ref().map_or_else(
                    || parameter.name.clone(),
                    |constraint| format!("{} is {constraint}", parameter.name)
                ))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn param_name(param: &Param) -> String {
    param.ty.as_ref().map_or_else(
        || param.name.clone(),
        |ty| format!("{} is {}", param.name, type_name(ty)),
    )
}

fn field_name(field: &FieldDef) -> String {
    format!("{} is {}", field.name, type_name(&field.ty))
}

fn type_name(reference: &TypeRef) -> String {
    match reference {
        TypeRef::Named(name, _) => name.clone(),
        TypeRef::Applied(name, arguments, _) => format!(
            "{name}<{}>",
            arguments
                .iter()
                .map(type_name)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        TypeRef::Array(element, _) => format!("[{}]", type_name(element)),
        TypeRef::Nullable(inner, _) => format!("{}?", type_name(inner)),
        TypeRef::Result(ok, error, _) => {
            format!("Result<{}, {}>", type_name(ok), type_name(error))
        }
    }
}
