use crate::ast::{FieldDef, Param, Stmt, TypeRef};

pub fn generate(package: &str, version: &str, program: &[Stmt]) -> String {
    let mut output = format!(
        "# {package} {version} API\n\nGenerated by Nivren {}.\n",
        crate::VERSION
    );
    document_modules(program, &mut output);
    output
}

fn document_modules(statements: &[Stmt], output: &mut String) {
    for statement in statements {
        if let Stmt::Module {
            name,
            body,
            exports,
            ..
        } = statement
        {
            output.push_str(&format!("\n## Module `{name}`\n\n"));
            for export in exports {
                if let Some(declaration) =
                    body.iter().find(|item| declared_name(item) == Some(export))
                {
                    output.push_str(&format!("- {}\n", declaration_signature(declaration)));
                }
            }
            document_modules(body, output);
        }
    }
}

fn declared_name(statement: &Stmt) -> Option<&String> {
    match statement {
        Stmt::Let { name, .. }
        | Stmt::Function { name, .. }
        | Stmt::Record { name, .. }
        | Stmt::Enum { name, .. }
        | Stmt::Module { name, .. } => Some(name),
        _ => None,
    }
}

fn declaration_signature(statement: &Stmt) -> String {
    match statement {
        Stmt::Let {
            name, annotation, ..
        } => annotation.as_ref().map_or_else(
            || format!("`let {name}`"),
            |ty| format!("`let {name}: {}`", type_name(ty)),
        ),
        Stmt::Function {
            name,
            params,
            return_type,
            ..
        } => {
            let parameters = params.iter().map(param_name).collect::<Vec<_>>().join(", ");
            let result = return_type
                .as_ref()
                .map(|ty| format!(" -> {}", type_name(ty)))
                .unwrap_or_default();
            format!("`fun {name}({parameters}){result}`")
        }
        Stmt::Record { name, fields, .. } => {
            let fields = fields.iter().map(field_name).collect::<Vec<_>>().join(", ");
            format!("`record {name} {{ {fields} }}`")
        }
        Stmt::Enum { name, variants, .. } => {
            format!("`enum {name} {{ {} }}`", variants.join(", "))
        }
        Stmt::Module { name, .. } => format!("`module {name}`"),
        _ => "`unknown declaration`".into(),
    }
}

fn param_name(param: &Param) -> String {
    param.ty.as_ref().map_or_else(
        || param.name.clone(),
        |ty| format!("{}: {}", param.name, type_name(ty)),
    )
}

fn field_name(field: &FieldDef) -> String {
    format!("{}: {}", field.name, type_name(&field.ty))
}

fn type_name(reference: &TypeRef) -> String {
    match reference {
        TypeRef::Named(name, _) => name.clone(),
        TypeRef::Array(element, _) => format!("[{}]", type_name(element)),
        TypeRef::Nullable(inner, _) => format!("{}?", type_name(inner)),
        TypeRef::Result(ok, error, _) => {
            format!("Result<{}, {}>", type_name(ok), type_name(error))
        }
    }
}
